# Generated by Django 4.1.1 on 2022-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('last_mesured_date', models.DateField()),
                ('last_mesured_time', models.DateTimeField()),
                ('tempreture', models.CharField(max_length=10)),
                ('sensor_name', models.CharField(max_length=30)),
                ('sensor_model', models.CharField(max_length=30)),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
